project:
  type: website

website:
  title: ""
  back-to-top-navigation: true
  reader-mode: true
  page-footer: 
    right: "Copyright 2024"
  navbar:
    logo: images/housing index.png
    left: 
      - href: "Proposal/proposal.html"
        text: Proposal
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    page-layout: full
    theme: lux
    css: styles.css
    toc: true

about: 
  template: jolla
  id: about-block

editor: visual

