project:
  type: website

website:
  title: ""
  back-to-top-navigation: true
  reader-mode: true
  page-footer: 
    right: "Copyright 2024"
  navbar:
    logo: images/housing index.png
    left: 
      - href: "https://isss608-wmfu.shinyapps.io/VAAProject/"
        text: Shinyapp
      - href: "userguide/userguide.html"
        text: User Guide
      - href: "poster/poster.html"
        text: Poster
      - href: "Proposal/proposal.html"
        text: Proposal
      - href: "team/team.html"
        text: About the Creators
    right:
      - icon: house-door-fill
        href: index.qmd
        text: Home


format:
  html:
    page-layout: full
    theme: lux
    css: styles.css
    toc: true



editor: visual

